services:
  frontend:
    networks:
      - website-network
    build: 
      context: ./bevangelista-website
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
      dockerfile: Dockerfile
    env_file: ./bevangelista-website/.env
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: bevangelista-website
          target: /code
    command: "npm start"
  backend:
    networks:
      - website-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GCP_API_KEY=${GCP_API_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  website-network:
    driver: bridge