services:
  frontend:
    build: 
      context: ./bevangelista-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: bevangelista-website
          target: /code
    command: "npm start"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GCP_API_KEY=${GCP_API_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s