services:
  frontend:
    build: 
      context: ./bevangelista-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: bevangelista-website
          target: /code
    command: "npm start"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - GCP_API_KEY=AIzaSyCQA0Ya2YqWmo9P8O8Wh2RVUf72BSOvCZ0