services:
  frontend:
    build: 
      context: ./bevangelista-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: bevangelista-website
          target: /code
    command: "npm start"