name: Build and Publish Image to Docker Hub
on:
  push:
    branches:
    - 'feat/ghaSetup'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build ./bevangelista-website/ -t bkevangelista/personal-website-frontend:latest
      - name: Push Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push bkevangelista/personal-website-frontend:latest
