name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "GCP_API_KEY=${{ secrets.GCP_API_KEY }}" >> .env
          echo "GCP_PROJECT_ID=be-personal-website" >> .env
          echo "GCP_BUCKET_NAME=be-website-public" >> .env

      - name: Build Image
        run: |
          docker build ./bevangelista-website/ -t bkevangelista/personal-website-frontend:latest
          docker build ./backend/ -t bkevangelista/personal-website-backend:latest

      - name: Push Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push bkevangelista/personal-website-frontend:latest
          docker push bkevangelista/personal-website-backend:latest

  run-tests:
    runs-on: ubuntu-latest
    needs: publish_images

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Docker Compose
        run: docker compose up -d --build

      - name: Wait for Backend to Be Healthy
        run: |
          docker inspect --format='{{.State.Health.Status}}' personal-website-backend | grep -q "healthy"
          if [ $? -ne 0 ]; then
            echo "Backend service is not healthy!"
            exit 1
          fi

      - name: Run Tests
        run: docker compose exec -T backend pytest tests/ --disable-warnings

      - name: Stop Docker Containers
        run: docker compose down