name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish Image to Docker Hub
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GHA_TOKEN }}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/bkevangelista/Personal-Website/actions/workflows/docker-image.yml/dispatches

  run-tests:
    runs-on: ubuntu-latest
    needs: publish_images
    steps:
      - name: Run Tests After Docker Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GHA_TOKEN }}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/bkevangelista/Personal-Website/actions/workflows/run-tests.yml/dispatches