name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "GCP_API_KEY=${{ secrets.GCP_API_KEY }}" >> .env
          echo "GCP_PROJECT_ID=be-personal-website" >> .env
          echo "GCP_BUCKET_NAME=be-website-public" >> .env

      - name: Build Images
        run: |
          docker build ./bevangelista-website/ -t bkevangelista/personal-website-frontend:latest
          docker build ./backend/ -t bkevangelista/personal-website-backend:latest

      - name: Run Containers
        run: |
          docker run -d --name personal-website-frontend bkevangelista/personal-website-backend:latest
          docker run -d --name personal-website-backend bkevangelista/personal-website-backend:latest

  run_tests:
    runs-on: ubuntu-latest
    needs: build_images

    steps:
      - name: Run Tests
        run: docker compose exec -T backend pytest tests/ --disable-warnings

  publish_images:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Push Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push bkevangelista/personal-website-frontend:latest
          docker push bkevangelista/personal-website-backend:latest