name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish Image to Docker Hub
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'docker-image.yml'
          ref: 'main'

  run-tests:
    runs-on: ubuntu-latest
    needs: publish_images
    steps:
      - name: Run Tests After Docker Build
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'run-tests.yml'
          ref: 'main'