name: pull-request.yml

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_images_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "GCP_API_KEY=${{ secrets.GCP_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_BACKEND_API_URL=${{ secrets.BACKEND_URL }}" >> .env
          echo "GCP_PROJECT_ID=be-personal-website" >> .env
          echo "GCP_BUCKET_NAME=be-website-public" >> .env
        working-directory: ${{ github.workspace }}

      - name: Build and Test Containers
        run: |
          docker build ./bevangelista-website/ -t bkevangelista/personal-website-frontend:latest
          docker build ./backend/ -t bkevangelista/personal-website-backend:latest